# Generated by Django 5.0.2 on 2024-03-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalactivity',
            name='HALL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.hall'),
            preserve_default=False,
        ),
    ]
